baseurl = "https://example.com"
languageCode = "en"
title = "Nick Vernij's Blog"
theme = "Hucore"
copyright = "&copy; 2017 <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Powered by Hucore</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> â™¥"
disqusShortname = ""
googleAnalytics = "trackingcode"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "This is a blog where I talk about my experiences learning rust and my side/toy projects"
keywords = ["Rust"]
author = "Nick Vernij"
sharingicons = true

[params.highlight]
style = "github"
languages = ["rust", "javascript", "x86asm"]

[[params.social]]
url = "https://github.com/nickforall"
fa_icon = "fa-github"

[[params.social]]
url = "https://twitter.com/nickforallnl"
fa_icon = "fa-twitter"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"
